# Práctica Pandas

- Encuentre el percentil 95 de la magnitud del terremoto en Japón usando el tipo de magnitud `mb`.
- Encuentre el porcentaje de terremotos en Indonesia que se acompañaron de tsunamis.
- Calcule estadísticas resumidas para terremotos en Nevada.
- Agregue una columna que indique si el terremoto ocurrió en un país o estado de EE. UU. Que se encuentra en el "Anillo de fuego". - Utilice Alaska, Antarctica (buscar por Antarctic), Bolivia, California, Canada, Chile, Costa Rica, Ecuador, Fiji, Guatemala, Indonesia, Japan, Kermadec Islands, Mexico (no es New Mexico), New Zealand, Peru, Philippines, Russia, Taiwan, Tonga, and Washington.
- Calcula el número de terremotos en las ubicaciones del Anillo de Fuego y el número fuera de ellos.
- Encuentra el recuento de tsunamis a lo largo del Anillo de fuego.

In [1]:
# Importar librerías
import numpy as np
import pandas as pd
import datetime as dt

In [79]:
# Cargamos archivo de github
ruta = 'https://raw.githubusercontent.com/CatuCerecedo/Bootcamp_DataScience_student/master/week10/data/parsed.csv'
df = pd.read_csv(ruta)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   alert         59 non-null     object
 1   cdi           329 non-null    float64
 2   code          9332 non-null   object
 3   detail        9332 non-null   object
 4   dmin          6139 non-null   float64
 5   felt          329 non-null    float64
 6   gap           6164 non-null   float64
 7   ids           9332 non-null   object
 8   mag           9331 non-null   float64
 9   magType       9331 non-null   object
 10  mmi           93 non-null     float64
 11  net           9332 non-null   object
 12  nst           5364 non-null   float64
 13  place         9332 non-null   object
 14  rms           9332 non-null   float64
 15  sig           9332 non-null   int64
 16  sources       9332 non-null   object
 17  status        9332 non-null   object
 18  time          9332 non-null   int64
 19  title         9332 non-null   object
 20  tsunami       9332 non-null   int64
 21  type          9332 non-null   object
 22  types         9332 non-null   object
 23  tz            9331 non-null   float64
 24  updated       9332 non-null   int64
 25  url           9332 non-null   object
 26  parsed_place  9332 non-null   object
dtypes: float64(9), int64(4), object(14)
memory usage: 1.9+ MB

In [9]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01806,NaN,185.0,",nc73086771,",0.62,md,...,reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...,California
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.03041,NaN,50.0,",ci38063967,",1.00,ml,...,reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...,California
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.45260,NaN,276.0,",pr2018261000,",2.40,md,...,reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...,Puerto Rico
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01865,NaN,61.0,",ci38063959,",1.10,ml,...,reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...,California
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01698,NaN,39.0,",ci38063935,",0.66,ml,...,reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [64]:
# Percentil 95 de la magnitud del terremoto en Japón usando el tipo de magnitud `mb`
# p95 = df[(df['magType'] == 'mb') & (df['parsed_place'] == 'Japan') & (df['type'] == 'earthquake')]['mag'].describe(percentiles=[0.05, 0.95])[6]
p95 = df[(df['magType'] == 'mb') & (df['parsed_place'] == 'Japan')]['mag'].describe(percentiles=[0.05, 0.95])[6]
print(f'Percentil 95 de la magnitud del terremoto en Japón usando el tipo de magnitud `mb`: {p95}')

#... Alternativa con método quantile de pd
# df[(df['magType'] == 'mb') & (df['parsed_place'] == 'Japan')]['mag'].quantile(0.95)

Percentil 95 de la magnitud del terremoto en Japón usando el tipo de magnitud `mb`: 4.9

count    50.000000
mean      4.530000
std       0.266688
min       4.000000
5%        4.100000
50%       4.600000
95%       4.900000
max       5.400000
Name: mag, dtype: float64

In [30]:
# Encuentre el porcentaje de terremotos en Indonesia que se acompañaron de tsunamis.
# ¿Teniendo en cuenta Indonesia como el total?
total_indonesia = len(df[(df['type'] == 'earthquake') & (df['parsed_place'] == 'Indonesia')])
tsunami = len(df[(df['type'] == 'earthquake') & (df['parsed_place'] == 'Indonesia') & (df['tsunami'] == 1)])
print(f'El total de terremotos en indonesia fue de {total_indonesia}, de los cuales con tsunami se contabilizaron {tsunami}.\n El procentaje de terremotos con tsunami fue de {round(tsunami/total_indonesia*100, 2)}%')

El total de terremotos en indonesia fue de 147, de los cuales con tsunami se contabilizaron 34.
 El procentaje de terremotos con tsunami fue de 23.13%

In [66]:
#...Alternativa
f"{df[df['parsed_place'] == 'Indonesia']['tsunami'].value_counts(normalize=True).iloc[1,]:.2%}"

'23.13%'

In [67]:
# Calcule estadísticas resumidas para terremotos en Nevada.
df[(df['type'] == 'earthquake') & (df['parsed_place'] == 'Nevada')].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,14.000000,647.000000,14.000000,647.000000,647.000000,1.00,647.000000,647.000000,647.000000,6.470000e+02,647.0,647.0,6.470000e+02
mean,2.421429,0.163155,2.500000,154.436615,0.437311,2.84,12.704791,0.140627,9.146832,1.538318e+12,0.0,-480.0,1.538409e+12
std,0.514675,0.161793,4.783787,69.474945,0.653397,NaN,10.052695,0.056765,17.939055,5.954980e+08,0.0,0.0,5.991682e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537323e+12
25%,2.000000,0.053000,1.000000,97.295000,-0.100000,2.84,6.000000,0.104400,0.000000,1.537859e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.109000,1.000000,150.040000,0.300000,2.84,9.000000,0.142900,1.000000,1.538286e+12,0.0,-480.0,1.538428e+12
75%,3.000000,0.223000,1.000000,200.515000,0.800000,2.84,16.000000,0.181050,10.000000,1.538824e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.340000,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [ ]:
# Agregue una columna que indique si el terremoto ocurrió en un país o estado de EE. UU. Que se encuentra en el "Anillo de fuego". 
# Utilice Alaska, Antarctica (buscar por Antarctic), Bolivia, California, Canada, Chile, Costa Rica, Ecuador, Fiji, 
# Guatemala, Indonesia, Japan, Kermadec Islands, Mexico (no es New Mexico), New Zealand, Peru, Philippines, Russia, Taiwan, Tonga, and Washington.
cols = ['Alaska', 'Antarctic', 'Bolivia', 'California', 'Canada', 'Chile', 'Costa Rica', 'Ecuador', 'Fiji', 
 'Guatemala', 'Indonesia', 'Japan', 'Kermadec Islands', 'Mexico', 'New Zealand', 'Peru', 'Philippines', 'Russia', 'Taiwan', 'Tonga', 'Washington']

df['ring fire'] = df['parsed_place'].isin(cols) 
df.sample(20, random_state=17)

In [77]:
#...Alternativa. Cuando quieres buscar patrones
df['alter'] = df['parsed_place'].str.contains(r'|'.join([
    'Alaska', 'Antarctic', 'Bolivia', 'California', 'Canada', 'Chile', 'Costa Rica', 'Ecuador', 'Fiji', 
 'Guatemala', 'Indonesia', 'Japan', 'Kermadec Islands', '^Mexico', 'New Zealand', 'Peru', 'Philippines', 
 'Russia', 'Taiwan', 'Tonga', 'Washington'
]))

Empty DataFrame
Columns: [alert, cdi, code, detail, dmin, felt, gap, ids, mag, magType, mmi, net, nst, place, rms, sig, sources, status, time, title, tsunami, type, types, tz, updated, url, parsed_place, ring fire, alter]
Index: []

[0 rows x 29 columns]

In [47]:
# Calcula el número de terremotos en las ubicaciones del Anillo de Fuego y el número fuera de ellos.
eq_out = len(df[(df['type'] == 'earthquake') & (df['ring fire'] == False)])
eq_in =  len(df[(df['type'] == 'earthquake') & (df['ring fire'] == True)])

print(f'Número de terremotos:\n - Dentro del anillo: {eq_in}\n - Fuera del anillo: {eq_out}')

Número de terremotos:
 - Dentro del anillo: 7000
 - Fuera del anillo: 2081

In [82]:
#...Alternativa
df[(df['type'] == 'earthquake')]['ring fire'].value_counts()

True     7000
False    2081
Name: ring fire, dtype: int64

In [49]:
# Encuentra el recuento de tsunamis a lo largo del Anillo de fuego.
tsunami_ring = len(df[(df['ring fire'] == True) & (df['tsunami'] == 1)])
print(f'Se produjeron un total de {tsunami_ring} tsunamis en el Anillo de Fuego')

Se produjeron un total de 45 tsunamis en el Anillo de Fuego

In [83]:
#...Alternativa
df.loc[df['ring fire'], 'tsunami'].sum()

45